### ISSUE TITLE
No more access to parameters

### ISSUE THREAD

**Issue by chtixof** [captainepoch/husky#105]
## General description of the issue

When the banner is removed, via the parameters, it also removes the access to the parameters and there is no way (at least, I found no way) to set the banner back.

## Husky information

- Husky version: 1.5.3
- Android version: EMUI 12.0.0

## Steps to reproduce it

1. Disable the display of the banner via the settings 
2. That's all

## Where did you get Husky from:

- [X] F-Droid.
- [ ] Self-releases.
- [ ] Play Store.
- [ ] Self-compiled (specify tag/commit).

**Comment by captainepoch** [comment]
What banner? Can you share a screenshot, please?

**Comment by captainepoch** [comment]
That's not a banner. It's the header. You have a lateral menu if you swipe from left to right from the border of the screen, and you can access to the options and Preferences sections.

**Comment by chtixof** [comment]
Thanks. I could grab it after several trials. Most of the time, on my phone, this left to right swap from the border of the screen displays a global menu, as in this screenshot. But OK, I could restore the header.
![Screenshot_20240905_162308_su xash husky](https://github.com/user-attachments/assets/3b86d219-b1f2-4115-9f99-a91d251ddc51)

**Comment by captainepoch** [comment]
That is out of my control, it's a personalized UI experience of your manufacturer and cannot fix that kind of behavior. Sorry about that.

I'll close this issue. Cheers!
