### ISSUE TITLE
Error report template

### ISSUE THREAD

**Issue by comradekingu** [captainepoch/husky#69]
>You acknowledge, opening this issue, that you read Codeberg's ToS and the
>content you upload meets to the requirements.
>
>Please see `<CONTRIBUTING>`.

Link to those if that is the case?

**Comment by captainepoch** [comment]
Sorry, this repository is migrated from Codeberg and there are a few things being WIP, one of those is just that link. I'll update the template as soon as I migrate that part of the documentation.
