### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [captainepoch/husky#70]
https://hosted.weblate.org/projects/husky/translations/#information
says GPLv3-`only`, which creates problems over '`or-later`' when specified explicitly.
The repo doesn't seem to do one or the other, but doing "only" for the translations creates an
incompatibility.

Negotiating with each individual translator to move to AGPLv3+/GPLv4 seems worse.

Can be fixed in

https://hosted.weblate.org/settings/husky/translations
and
https://hosted.weblate.org/settings/husky/glossary

**Comment by captainepoch** [comment]
I don't intend to change the license to `or-later` at any moment, though, that's why it's not specified in any part.

**Comment by captainepoch** [comment]
Also, I didn't see Weblate provides more than `-only` or `-or-later` options for GPL, that's why I chose `-only`.

**Comment by captainepoch** [comment]
No new comment since April, this issue is closed. Feel free to open it again.

Cheers!

**Comment by comradekingu** [comment]
I don't understand. It is either `-only`, or `-or-later`.
There is no mention of `-only` here, so it effectively becomes limiting to specify it for part of what goes into the codebase.

`-only` only has utility if you want to prevent combining it with other works, or not having the option to go GPLv4 in the future, etc.

**Comment by captainepoch** [comment]
I don't think this project needs to contemplate going GPLv4 because it'd be almost impossible to get to every Tusky maintainer asking permission for it, so I think it's safe to assume `-only`.

**Comment by comradekingu** [comment]
I think the opposite is true. The default doesn't state it, whereas it would only require to add the note.

Conversely, adding an "-`only`" taints all future forks and combined works.
