### ISSUE TITLE
Husky crashes if I try to load some images

### ISSUE THREAD

**Issue by alan-ford** [captainepoch/husky#73]
## General description of the issue

If I try to load some pictures Husky suddenly closes. In this case the problem occurs with images downloaded from Facebook. To solve this I have to open them with any photo editing programme and export them.

## Husky information

- Husky version: 1.5.4.
- Android version: 7.1.2

If you think it is an instance-related issue, please specify the instance.

- Instance: orwell.fun

## Steps to reproduce it

Please, describe the steps to reproduce the issue:

1. Download any image from Facebook;
2. Upload it in a post.

This is one of the images that caused a crash:

![FB_IMG_17149440648904125](https://github.com/captainepoch/husky/assets/44990009/d2cc015b-a231-4f4f-8830-657c80c3573a)

## Where did you get Husky from:

- [x] F-Droid.
- [ ] Self-releases.
- [ ] Play Store.
- [ ] Self-compiled (specify tag/commit).

**Comment by captainepoch** [comment]
Could you provide a couple more of images, please? Thanks!

**Comment by alan-ford** [comment]
Here are two images that created problems for Husky:

![2352](https://github.com/captainepoch/husky/assets/44990009/58108798-b43f-4ce0-9985-97e17b09f1ef)
![2395](https://github.com/captainepoch/husky/assets/44990009/ee6ddd86-806e-457f-872c-5a468ff8beb5)

**Comment by captainepoch** [comment]
Thanks!

**Comment by captainepoch** [comment]
Still waiting for an account in the mentioned instance.

**Comment by captainepoch** [comment]
Your admin deleted my request for an account in that instance, and thus, I cannot reproduce nor fix this issue.

If you find another instance, or you're willing to speak with your admin about this, reopen this issue.

Cheers, thank you.
