### ISSUE TITLE
1.6.0-beta1.1: cannot attach media to post

### ISSUE THREAD

**Issue by tehcaster** [captainepoch/husky#78]
After selecting the media file(s), it says "The upload failed." in a bar on the bottom. Works OK in 1.5.x

**Comment by captainepoch** [comment]
It'd be better if you didn't delete the template, it's there for a reason.

**Comment by captainepoch** [comment]
This is a known bug for beta version because of OkHttp. Please read https://github.com/captainepoch/husky/wiki/Beta-versions.
