### ISSUE TITLE
1.6.0-beta1.1: quoted toots appear under many unrelated toots

### ISSUE THREAD

**Issue by tehcaster** [captainepoch/husky#79]
Once a legitimate quote toot appears in my timeline, I can see it also under many unrelated ones that didn't quote it. No idea what the conditions are. Example below.

![Screenshot_20240606-115818-049](https://github.com/captainepoch/husky/assets/9321878/16bc17b4-ee08-43c2-96df-5e1fe66950d8)

**Comment by captainepoch** [comment]
It'd be better if you didn't delete the template, it's there for a reason.

**Comment by captainepoch** [comment]
It's a weird bug, I'll take a look asap. Thanks!
