### ISSUE TITLE
Husky Beta crashes when opening a specific user profiles in pixelfed.uno

### ISSUE THREAD

**Issue by lichingyun** [captainepoch/husky#88]
## General description of the issue

I am using the latest Husky Beta 1.6.0. - beta 2.
the Beta crashes only when opening a specific user profiles in pixelfed.uno (the italian instance of pixelfed).
The user profile is @Manhattan@pixelfed.uno, if I open others profiles in pixelfed.uno or in other  instances (pixelfed social, pixelfed.eu) the Beta don't crash.
This crash happen also using the old beta and the latest stable from Fdroid 
This crash doesn't happen using different app (Pixeldroid, Pixelfed, Fedilab)

## Husky information

- Husky version: 1.6.0. - beta 2
- Android version: 13 on OnePlus Nord 2

If you think it is an instance-related issue, please specify the instance.

- Instance: pixelfed.uno

## Steps to reproduce it

1. login in pixelfed.uno
2. open the user profile @Manhattan@pixelfed.uno
3. Husky Beta crash and close

## Where did you get Husky from:

- [x] F-Droid.
- [X] Self-releases.
- [ ] Play Store.
- [ ] Self-compiled (specify tag/commit).

**Comment by captainepoch** [comment]
I'm guessing you're trying to open that profile from another account and not logging into Pixelfed using Husky, am I right?

**Comment by lichingyun** [comment]
> I'm guessing you're trying to open that profile from another account and not logging into Pixelfed using Husky, am I right?

no, I was using Husky Beta and I was logged into pixelfed.uno from Husky Beta 🙏
The beta crashed only when open that profile, its a strange thing

**Comment by captainepoch** [comment]
Husky doesn't support Pixelfed as it, but I can take a look into it, it might affect other platforms.

**Comment by lichingyun** [comment]
> Husky doesn't support Pixelfed as it, but I can take a look into it, it might affect other platforms.

Many thanks, in the latest 2 years and half I have nearly used Husky or Husky Beta for Mastodon and Pixelfed, this is the first  problem I see 🙏

**Comment by captainepoch** [comment]
I'm working now on another issue, but I'll get to this as soon as I finish.

Oh, nice to know you didn't have any problems. Cheers!

**Comment by lichingyun** [comment]
Hello Adolph, I upgraded to the new beta 1.6.0. beta 3 and this issue is present, also is not possible to upload pictures (from the camera and from the telephone) to Pixelfed instances 🙏

**Comment by captainepoch** [comment]
Because I didn't fix it, the only changes are those in the changelog. I'm still looking for a fix for this (I already located the issue).

**Comment by lichingyun** [comment]
many thanks for your explanation, I don't have understand before 🙏🙏🙏 the problem with the media upload is also present in the stable version 1.5.4 🙏 thanks for your work, take your time
