### ISSUE TITLE
Top bar glitching when opening media

### ISSUE THREAD

**Issue by m1chj** [captainepoch/husky#93]
## General description of the issue

Top bar glitches when viewing media, both images and videos

## Husky information

- Husky version: 1.6.0
- Android version: 10

## Steps to reproduce it

Please, describe the steps to reproduce the issue:

1. Open any media, doesn't matter video or image
2. See top bar glitching: some elements disappear, some change color, some stay the same

https://github.com/user-attachments/assets/1a3d183a-a048-4182-a677-be76a4a5036c

Looks like it's is related to Huawei EMUI? Happens with system dark mode on and off and all Husky themes. Probably doesn't matter but it's the same issue with Tusky.

## Where did you get Husky from:

- [X] Self-releases.

**Comment by captainepoch** [comment]
I don't own a Huawei device, but I'll give a try. Thanks!
