### ISSUE TITLE
Husky does not allow attaching more than 4 files

### ISSUE THREAD

**Issue by Willt125** [captainepoch/husky#95]
Husky does not allow for attaching more than 4 media files, despite allowing it previously.

## Husky information

- Husky version: 1.6.0
- Android version: 14

## Steps to reproduce it

Please, describe the steps to reproduce the issue:

1. Open an instance that allows for >4 media attachments (Pleroma/Akkoma instances come to mind)
2. Attempt to attach >4 files (Whether all at once, or separately)

Husky throws "You cannot attach more than 4 media to a post".

## Where did you get Husky from:

- [x] F-Droid.
- [ ] Self-releases.
- [ ] Play Store.
- [ ] Self-compiled (specify tag/commit).

**Comment by captainepoch** [comment]
This is not a regression, this is hardcoded into the app because it's a fork of Tusky. Could you edit the title, please?
