### ISSUE TITLE
Clicking 'Open in browser' using Mitra account crashes Husky

### ISSUE THREAD

**Issue by watamelonman** [captainepoch/husky#97]
## General description of the issue

Pressing on the 'Open in browser' option crashes Husky if you're using a Mitra account on it. Either it suddenly closes, resets or you get a 'Husky has stopped working' dialog.

## Husky information

- Husky version: 1.6.0
- Android version: 14
- Android ROM: CalyxOS 5.9.0

If you think it is an instance-related issue, please specify the instance.

- Instance: mt.watamelon.win
- Instance software: Mitra 3.2.0

## Steps to reproduce it

Please, describe the steps to reproduce the issue:

1. Log into Mitra account on Husky
2. Click ... button on any post
3. Click 'Open in browser'

## Where did you get Husky from:

- [X] F-Droid.
- [ ] Self-releases.
- [ ] Play Store.
- [ ] Self-compiled (specify tag/commit).

**Comment by captainepoch** [comment]
The backend doesn't provide `url` but `uri`, which I don't understand why... I'll test and add a fix, but it shouldn't happen.

cc: @silverpill

**Comment by silverpill** [comment]
Mastodon API docs say it is a [nullable](https://docs.joinmastodon.org/entities/Status/#url) field. But I agree that null value makes little sense there, I'll change it to actual URL. Thanks for bringing this to my attention!

**Comment by captainepoch** [comment]
Yeah, but in Pleroma and Akkoma instances, the `url` has an actual `url` (at this very moment, not a single instance I've been using for testing crashed because of this, even Mastodon and Glitch), that's why I mentioned you, @silverpill 😃
