### ISSUE TITLE
Change the default color palette

### ISSUE THREAD

**Issue by daks-ua** [captainepoch/husky#98]
## Description of the feature

Allow user to change the default color palette of the application.

**Comment by captainepoch** [comment]
Not planned to add more themes into Husky.

**Comment by daks-ua** [comment]
That's fine, thanks for the honest reply. One more application gets to my ban list.

**Comment by captainepoch** [comment]
You can change the default theme going to Preferences, but no more themes than those will be available.

Cheers.

**Comment by daks-ua** [comment]
There is no possibility to get rid the yellow(ish) main accent color in themes. Personally I just don't like the color but I don't see a way to change it to another color in any theme. So no, that's not about adding new themes.
P.s.: I believe a lot of people with color blindness will support a request to have possibility to change the main accent color.
